---
- name: Configure Document Root Folder in Ubuntu
  copy: src=000-default.conf dest=/etc/apache2/sites-available/000-default.conf backup=yes

- name: Grant permission to Document Root Folder in Ubuntu
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf backup=yes
  notify:
    - Restart Apache Tomcat app server in Ubuntu
...
