---
# tasks file for tomcat
- include: "install-tomcat-{{ansible_distribution|lower}}.yml"
- include: common-tasks.yml
- include: "configure-tomcat-{{ansible_distribution|lower}}.yml"
- include: "start-tomcat-{{ansible_distribution|lower}}.yml"
...
