- name: Demonstrates the use of register variable 
  hosts: localhost
  tasks:
    - name: List the root directory contents
      shell: ls -l /tmp
      #shell: "curl http://localhost:8001" 
      register: output

    - name: Print the output register variable
      debug: var=output
