- name: This playbook demonstrates using our custom ansible module
  hosts: localhost
  tasks:
    - name: Invoke our hello ansible module
      hello: name="Custom Ansible Module!"
      register: output

    - debug: var=output
