- name: This playbook will install nginx, configure it and deploys web page into nginx
  hosts: all
  vars:
    - greeting_message: DevOps!
    - provisioner_tool: Docker
    - cm_tool: Ansible
  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes

    - name: Install Extra Packages for Enterprise Linux (EPEL) in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest 

    - name: Install nginx web server in CentOS
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest 

    - name: Create Document Root Folder
      file: path=/var/html state=directory mode=0777

    - name: Configure nginx document root folder in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default backup=yes

    - name: Configure nginx document root folder in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes

    - name: Restart the nginx web server
      #service: name=nginx state=restarted
      shell: service nginx restart

    - name: Deploy web page into nginx web server
      template: src=index.html.j2 dest=/var/html/index.html

- name: This is a second play
  hosts: localhost
  tasks:
    - name: Install curl utility
      apt: name=curl state=latest update_cache=yes

    - name: Test if the nginx web server is up and running 
      shell: "curl http://localhost:{{item}}"
      with_sequence: start=8001 end=8004
