- name: This playbook will build ansible ubuntu and centos images
  hosts: localhost
  vars:
    - ubuntu_image_name: "tektutor/ansible-ubuntu"
  tasks:
    - name: Install python pip utility
      apt: name=python-pip state=latest update_cache=yes

    - name: Install docker-py python library/package
      shell: pip install docker-py

    - name: Remove all existing containers
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: yes

    - name: Delete the existing Ansible Ubuntu image
      shell: "docker rmi {{ubuntu_image_name}}"
      ignore_errors: yes

    - name: Build Ansible ubuntu image
      docker_image:
           name: "{{ubuntu_image_name}}"
           state: build
           dockerfile: UbuntuDockerfile
           path: . 
